### PR TITLE
Fixes to hide the visibility of multiple copies of the explanation paragraph

### LINKED ISSUE #45: Make sure only one instance of the explanation paragraph is visible
Only show one instance of `<p>` in the case of multiple calculators being used

### PR DESCRIPTION
**Pull request by zeynepaki**
* Fixes #45

### CODE REVIEW

File: typescript/src/main.ts [hunk 1]
```diff
@@ -262,6 +262,18 @@ function downloadTableAsCsv(tableId: string, separator = ",") {
   document.body.removeChild(link);
 }
 
+function hideParagraphCopies() {
+  const paragraphs = Array.from(document.getElementsByTagName("p")).filter(
```
Comment (alisonrclarke) [inline typescript/src/main.ts:266]: Given the calculator could be inserted anywhere on a Wordpress site eventually, we should probably be more specific with this selector so it only gets children of a `.metalation-calculator` div (in case anyone decides to give another paragraph on the page a class of `intro`).

Or I guess the easier option would just be to change the p class from `intro` to `metalation-calculator-intro`?

File: typescript/src/main.ts [hunk 2]
```diff
@@ -262,6 +262,18 @@ function downloadTableAsCsv(tableId: string, separator = ",") {
...
+    (e) => e.className === "intro"
+  );
+  if (paragraphs.length > 1) {
+    paragraphs.shift();
```
Comment (alisonrclarke) [inline typescript/src/main.ts:270]: I think the code might be clearer if instead of removing the first item in the list, you just start with `x=1` on the next line. A comment would also be helpful.

File: typescript/src/main.ts [hunk 3]
```diff
@@ -262,6 +262,18 @@ function downloadTableAsCsv(tableId: string, separator = ",") {
   document.body.removeChild(link);
 }
 
+function hideParagraphCopies() {
```
Comment (alisonrclarke) [inline typescript/src/main.ts:265]: Could you add a comment explaining what this function does?

**Review by alisonrclarke — APPROVED** [review]

**Review by alisonrclarke — APPROVED** [review]
